config/routes.rb
Whitesnake::Application.routes.draw do
  root to: 'top#show'

  get '/login' => redirect('/auth/github'), :as => :login

  resource :profile, only: [ :show ]

  resources :repositories, only: [], id: %r[[^/]+/[^/]+] do
    resource :job, only: [ :create, :show, :destroy ]
  end

  controller :sessions do
    get '/auth/:provider/callback' => :create
    get '/auth/failure' => :failure
    get '/logout' => :destroy, as: :logout
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source Rails.root.join('config/settings.yml')
  namespace Rails.env

  def self.github_web_endpoint
    "https://#{github_web_authority_part}/"
  end

  def self.github_api_endpoint
    github.site
  end

  def self.github_authorize_url
    File.join(github_web_endpoint, "/login/oauth/authorize")
  end

  def self.github_token_url
    File.join(github_web_endpoint, "/login/oauth/access_token")
  end

  def self.github_enterprise?
    URI.parse(github.site).host != 'api.github.com'
  end

  def self.github_web_authority_part
    return 'github.com' unless github_enterprise?
    URI.parse(github.site).select(:host, :port).join(':')
  end

  def self.ci_host
    ci_uri.host
  end

  def self.ci_port
    ci_uri.port
  end

  def self.ci_endpoint_path
    ci_uri.path
  end

  def self.ci_uri
    URI.parse(ci.site)
  end
end

app/models/user.rb
require 'octokit_helper'

class User < ActiveRecord::Base
  include OctokitHelper::Model

  def self.from_omniauth(auth)
    user = where(auth.slice('provider', 'uid')).first || create_from_omniauth(auth)
    user.send :update_credentials, auth['credentials'] if user
    user
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['nickname']
    end
  end

  def each_repository(&block)
    return enum_for(:each_repository) unless block
    octokit_client.repositories(nil, type: 'owner').each(&block)
  end

  def repository(name)
    octokit_client.repository(owner: self.name, repo: name)
  end

  private

  def update_credentials(credentials)
    if self.token != credentials['token']
      self.token = credentials['token']
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Octokit::Error do |exception|
    Rails.logger.error "#{exception.class}: #{exception.message}"
    redirect_to logout_path
  end

  private

  def require_login
    return if current_user
    redirect_to root_path
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    not current_user.nil?
  end
  helper_method :logged_in?
end

app/controllers/jobs_controller.rb
require 'base64'
require 'octokit_helper'

class JobsController < ApplicationController
  include OctokitHelper::Controller

  before_action :fetch_job_setting, only: [ :create, :destroy ]

  def create
    response = Net::HTTP.start(Settings.ci_host, Settings.ci_port) do |http|
      job_name = job_name(@repository)
      http.post(File.join(Settings.ci_endpoint_path, "/createItem?name=#{CGI.escape job_name}"),
                config_xml(@job_setting, @repository).tap {|x| puts x},
                'Content-Type' => 'text/xml')
    end

    case response
    when Net::HTTPSuccess, Net::HTTPRedirection
      render json: { message: 'OK' }
    else
      render json: { message: "#{response.code} #{response.message}" }, status: response.code
    end
  end

  def destroy
    response = Net::HTTP.start(Settings.ci_host, Settings.ci_port) do |http|
      job_name = job_name(@repository)
      http.post(File.join(Settings.ci_endpoint_path, "/job/#{CGI.escape job_name}/doDelete"), '')
    end
    case response
    when Net::HTTPSuccess, Net::HTTPRedirection
      render json: { message: 'OK' }
    else
      render json: { message: "#{response.code} #{response.message}" }, status: response.code
    end
  end

  private

  def fetch_job_setting
    @repository = octokit_client.repository(params[:repository_id])
    response = octokit_client.content(params[:repository_id], path: '.whitesnake.yml')
    if response[:type] == 'file'
      case response[:encoding]
      when 'base64'
        content = Base64.decode64(response[:content])
      else
        content = response[:content]
      end
      @job_setting = Psych.load(content)
    end
    @job_setting = default_job_setting(@repository).update(@job_setting || {})
  rescue => error
    p error
    render json: { message: error.message }, status: 404
  end

  def default_job_setting(repository)
    {
      'branches' => %w[origin/master],
      'rbenv'    => %w[system],
      'script'   => %w[bundle && bundle exec rake spec],
    }
  end

  def job_name(repository)
    view_context.job_name(repository)
  end

  def config_xml(job_setting, repository)
    render_to_string 'jobs/config', layout: false, locals: { job_setting: job_setting, repository: repository }
  end
end

app/controllers/profiles_controller.rb
require 'json'

class ProfilesController < ApplicationController
  before_action :require_login

  def show
    @jobs = Net::HTTP.start('localhost', 8080) do |http|
      response = http.get("/api/json?tree=jobs[name,url]")
      data = JSON.load(response.body)
      data['jobs'].inject({}) do |hash, job|
        hash.update(job['name'] => job)
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: 'Logged in'
  end

  def failure
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def show
    if logged_in?
      redirect_to profile_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def combined_scripts(job_setting)
    [ rbenv_setup_script,
      %w[before_script script after_script].reject {|type|
        job_setting[type].nil? || job_setting[type].strip.empty?
      }.map {|type|
        "# #{type}\n" + [job_setting[type]].join("\n") + "\n"
      },
    ].join("\n")
  end

  def rbenv_setup_script
    <<-'EOS'
PATH=~/.rbenv/bin:$PATH
eval "$(rbenv init -)"
    EOS
  end

  def job_name(repository)
    [
      repository[:owner][:login],
      repository[:name],
    ].join('.')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/config.xml.slim
doctype xml
matrix-project
  actions/
  description
  keepDependencies
    | false

  properties
    <com.coravy.hudson.plugins.github.GithubProjectProperty plugin="github@1.5">
      projectUrl = repository[:html_url]
    </com.coravy.hudson.plugins.github.GithubProjectProperty>

  scm class="hudson.plugins.git.GitSCM" plugin="git@1.3.0"
    configVersion
      | 2
    userRemoteConfigs
      <hudson.plugins.git.UserRemoteConfig>
        name
        refspec
        url = repository[:ssh_url]
      </hudson.plugins.git.UserRemoteConfig>
    branches
      - job_setting['branches'].each do |branch|
        <hudson.plugins.git.BranchSpec>
          name = branch
        </hudson.plugins.git.BranchSpec>
    disableSubmodules
      | false
    recursiveSubmodules
      | false
    doGenerateSubmoduleConfigurations
      | false
    authorOrCommitter
      | false
    clean
      | false
    wipeOutWorkspace
      | false
    pruneBranches
      | false
    remotePoll
      | false
    ignoreNotifyCommit
      | false
    useShallowClone
      | false
    buildChooser class="hudson.plugins.git.util.DefaultBuildChooser"/
    gitTool
      | System Git
    browser class="hudson.plugins.git.browser.GithubWeb"
      url = repository[:html_url]
    submoduleCfg class="list"/
    relativeTargetDir
    reference
    excludedRegions
    excludedUsers
    gitConfigName
    gitConfigEmail
    skipTag
      | true
    includedRegions
    scmName

  / TODO: substitute label expression
  assignedNode = 'master'
  canRoam
    | false
  disabled
    | false
  blockBuildWhenDownstreamBuilding
    | false
  blockBuildWhenUpstreamBuilding
    | false
  triggers class="vector"
    - if false
      <hudson.triggers.TimerTrigger>
        spec = timmer_trigger_spec
      </hudson.triggers.TimerTrigger>
    <hudson.triggers.SCMTrigger>
      spec
        | H * * * *
      ignorePostCommitHooks
        | false
    </hudson.triggers.SCMTrigger>
  concurrentBuild
    | false

  axes/

  builders
    <hudson.tasks.Shell>
      command
        = combined_scripts(job_setting)
    </hudson.tasks.Shell>

  publishers
    - if false
      <hudson.publishers.rubyMetrics.rcov.RcovPublisher plugin="rubyMetrics@1.5.0">
        reportDir
          = rcov_report_directory
        targets
          - each_rcov_metric_target do |metric_target|
            hudson.plugins.rubyMetrics.rcov.model.MetricTarget
              metric = metric_target.metric
              healthy = metric_target.healthy
              unhealthy = metric_target.unhealthy
              unstable = metric_target.unstable
      </hudson.publishers.rubyMetrics.rcov.RcovPublisher>

  buildWrappers
    <hudson.plugins.build__timeout.BuildTimeoutWrapper plugin="build-timeout@1.11">
      timeoutMinutes
        | 10
      failBuild
        | false
      writingDescription
        | false
      timeoutPercentage
        | 0
      timeoutType
        | absolute
      timeoutMinutesElasticDefault
        | 3
    </hudson.plugins.build__timeout.BuildTimeoutWrapper>
    <hudson.plugins.timestamper.TimestamperBuildWrapper plugin="timestamper@1.5.3" />
    <hudson.plugins.ansicolor.AnsiColorBuildWrapper plugin="ansicolor@0.2.2-SNAPSHOT" />

  executionStrategy class="hudson.matrix.DefaultMatrixExecutionStrategyImpl"
    runSequentially
      | false

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Whitesnake"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", media: "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'



  body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Whitesnake
          .container-fluid.nav-collapse
            ul.nav.pull-right
              li.divider-vertical
              - if current_user
                li.navbar-text
                  | Logged in as
                  =< current_user.name
                li.divider-vertical
                li
                  =< link_to 'Log out', logout_path
              - else
                li
                  = link_to "Log in with GitHub#{Settings.github_enterprise? ? ' Enterprise' : ''}", '/auth/github'

    .container-fluid

      .row-fluid
        .span2
        .span8
          = bootstrap_flash
          = yield

      footer
        p &copy; Kenta Murata 2013
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/profiles/show.html.slim
h2 Repositories
table.table.table-striped
  tbody#repositories
    - current_user.each_repository do |repo|
      tr
        td= link_to repo[:full_name], repo[:html_url], rel: 'tooltip', title: repo[:description]
        td
          - job = @jobs[job_name(repo)]
          = form_tag repository_job_path(repo[:full_name]), id: "repository-#{repo[:full_name]}", class: 'repository-form', remote: true do
            i.icon-spinner.icon-spin.icon-large.pull-right.hidden
            .switch.switch-mini.hidden.pull-right
              input type="checkbox" data-form-id="repository-#{repo[:name]}" checked=(job && true)
            a.ci-link.pull-right.hidden href=(job && job['url']) title=(job && "Go to #{job['name']} job page")
              i.icon-flag

app/views/top/show.html.slim
h1 Whitesnake

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim
table.table.table-striped
  tbody#repositories
    - current_user.each_repository do |repo|
      tr
        td= link_to repo[:full_name], repo[:html_url], rel: 'tooltip', title: repo[:description]
        td
          = form_tag repository_job_path(repo[:full_name]), id: "repository-#{repo[:full_name]}", class: 'repository-form', remote: true do
            i.icon-spinner.icon-spin.icon-large.pull-right.hidden
            .switch.switch-mini.hidden.pull-right
              input type="checkbox" data-form-id="repository-#{repo[:name]}"